# Generated by Django 4.1.1 on 2022-10-12 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myprint', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderform',
            name='price_free_VAT',
        ),
        migrations.RemoveField(
            model_name='orderform',
            name='total_price_with_VAT',
        ),
    ]
