# Generated by Django 4.1.1 on 2022-10-10 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprint', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='name',
            field=models.CharField(max_length=65, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='media/category_image', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=65, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='ceo',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='ceo',
            name='image',
            field=models.ImageField(upload_to='media/ceo', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='ceo',
            name='name',
            field=models.CharField(max_length=65, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='ceo',
            name='number',
            field=models.IntegerField(verbose_name='number'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='image',
            field=models.ImageField(upload_to='media/contact', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='info',
            field=models.CharField(max_length=65, verbose_name='info'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=65, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='number',
            field=models.IntegerField(verbose_name='number'),
        ),
        migrations.AlterField(
            model_name='infoproduct',
            name='element',
            field=models.CharField(max_length=65, verbose_name='element'),
        ),
        migrations.AlterField(
            model_name='infoproduct',
            name='size',
            field=models.CharField(max_length=65, verbose_name='size'),
        ),
        migrations.AlterField(
            model_name='infotype',
            name='double_site_print',
            field=models.CharField(max_length=65, verbose_name='double_site_print'),
        ),
        migrations.AlterField(
            model_name='infotype',
            name='one_site_print',
            field=models.CharField(max_length=65, verbose_name='one_site_print'),
        ),
        migrations.AlterField(
            model_name='infotype',
            name='size',
            field=models.CharField(max_length=65, verbose_name='size'),
        ),
        migrations.AlterField(
            model_name='infotype',
            name='type_paper',
            field=models.CharField(max_length=65, verbose_name='type_paper'),
        ),
        migrations.AlterField(
            model_name='menuservice',
            name='image',
            field=models.ImageField(upload_to='media/menuservice', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='menuservice',
            name='name',
            field=models.CharField(max_length=65, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='menutariff',
            name='image',
            field=models.ImageField(upload_to='media/imagesTariff', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='menutariff',
            name='name',
            field=models.CharField(max_length=65, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(upload_to='media/portfolio', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='name',
            field=models.CharField(max_length=65, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='image',
            field=models.ImageField(upload_to='media/printer', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='name',
            field=models.CharField(max_length=65, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='media/product', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=65, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='image',
            field=models.ImageField(upload_to='media/social_media', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='name',
            field=models.CharField(max_length=65, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='number',
            field=models.IntegerField(verbose_name='number'),
        ),
        migrations.AlterField(
            model_name='sponsors',
            name='image',
            field=models.ImageField(upload_to='media/sponsor', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='sponsors',
            name='name',
            field=models.CharField(max_length=65, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='name',
            field=models.CharField(max_length=65, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(max_length=65, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='typeservice',
            name='name',
            field=models.CharField(max_length=65, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=64, verbose_name='first_name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=64, verbose_name='full_name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.IntegerField(blank=True, unique=True, verbose_name='phone_number'),
        ),
    ]
