# Generated by Django 4.1 on 2022-10-14 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myprint", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderform",
            old_name="student",
            new_name="customer",
        ),
        migrations.RemoveField(
            model_name="orderform",
            name="total_price_ALL",
        ),
        migrations.RemoveField(
            model_name="orderform",
            name="total_price_with_VAT",
        ),
        migrations.AlterField(
            model_name="orderform",
            name="VAT",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="orderform",
            name="amount",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="orderform",
            name="price",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
