# Generated by Django 4.1.1 on 2022-10-10 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprint', '0002_alter_banner_name_alter_category_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=65)),
                ('status_order', models.CharField(blank=True, choices=[('шт', 'шт'), ('усл', 'усл')], default='шт', max_length=20, null=True)),
                ('amount', models.IntegerField()),
                ('price', models.PositiveIntegerField()),
                ('price_free_VAT', models.PositiveIntegerField()),
                ('VAT', models.FloatField()),
                ('price_with_VAT', models.PositiveIntegerField()),
                ('total', models.PositiveIntegerField()),
                ('total_price_with_VAT', models.PositiveIntegerField()),
                ('total_price_ALL', models.PositiveIntegerField()),
            ],
        ),
    ]
