# Generated by Django 4.1.1 on 2022-10-10 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprint', '0003_orderform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_name_order', models.CharField(max_length=300)),
                ('name_client', models.CharField(max_length=65)),
                ('client_phone_number', models.CharField(max_length=65)),
                ('manager_name', models.CharField(max_length=65)),
                ('date_order', models.DateTimeField(auto_now_add=True)),
                ('ready_product_date_order', models.DateTimeField()),
            ],
        ),
    ]
